### ISSUE TITLE
Repair

### ISSUE THREAD

**Issue by d1ksu** [EternalCodeTeam/EternalCore#100]
Z tego co przejrzalem to repair macie zle zrobione poniewaz jesli item ma z reguly inne durability niz 0 to ustawi mu na 0, czyli np. koxa zmieni na refila, czerwone szklo na biale itd. Mozna to zmienic sprawdzajac maxstacksize bo narzedzia maja 1.

**Comment by vLuckyyy** [comment]
Dzięki, za zgłoszenie. Sprawdzimy to jak najszybciej się da, również zapraszamy do stworzenia PullRequesta 😄!

**Comment by Osnixer** [comment]
> 

Tak tylko nie zwróciłeś uwagi, że EternalCore wspiera tylko 1.17.x do góry, jak mnie pamięć nie myli **item data** została usunięta w 1.13+
