### ISSUE TITLE
Home database save issue

### ISSUE THREAD

**Issue by failutee** [EternalCodeTeam/EternalCore#436]
**To Reproduce**
- Create the maximum number of homes
- Restart server
- Delete one or more homes & create another one
- Restart server and you'll see that the home you deleted is back

**This way you can bypass the maximum number of homes**

![Zrzut ekranu 2023-05-07 151140](https://user-images.githubusercontent.com/50597234/236680087-8543efab-2b51-481f-bb5a-b44401aa805d.png)

![Zrzut ekranu 2023-05-07 151259](https://user-images.githubusercontent.com/50597234/236680089-3ba80614-2618-4f99-ba0c-b599146c4b5b.png)

![Zrzut ekranu 2023-05-07 151507](https://user-images.githubusercontent.com/50597234/236680090-894b4061-800b-4b3c-8bb5-e4c3f28fc286.png)

**Comment by Jakubk15** [comment]
Does the home simply pop-up on command suggestion, or you can practically use it, e.g. teleport to it?

**Comment by failutee** [comment]
> Does the home simply pop-up on command suggestion, or you can practically use it, e.g. teleport to it?

I can teleport to it

**Comment by Jakubk15** [comment]
> > Does the home simply pop-up on command suggestion, or you can practically use it, e.g. teleport to it?
> 
> I can teleport to it

Are you receiving any errors/warnings/logs in the console, that may help us accelerate fixing the issue? Do you have any solutions for it? Any workarounds?

**Comment by Jakubk15** [comment]
(probably due to poor caching), the algorithm is checking player homes in a runtime object, which is deleted on server stop, instead of relying on fetching homes from database

**Comment by failutee** [comment]
> > > Does the home simply pop-up on command suggestion, or you can practically use it, e.g. teleport to it?
> > 
> > 
> > I can teleport to it
> 
> Are you receiving any errors/warnings/logs in the console, that may help us accelerate fixing the issue? Do you have any solutions for it? Any workarounds?

There are no errors or warnings in the console

**Comment by failutee** [comment]
> (probably due to poor caching), the algorithm is checking player homes in a runtime object, which is deleted on server stop, instead of relying on fetching homes from database

This is a problem with deleting home from the database, even though I deleted it, it still appears in the database

![image](https://user-images.githubusercontent.com/50597234/236694312-ca543a25-2cf4-4ffa-9a70-510f8e50ec6f.png)

**Comment by Jakubk15** [comment]
> > (probably due to poor caching), the algorithm is checking player homes in a runtime object, which is deleted on server stop, instead of relying on fetching homes from database
> 
> This is a problem with deleting home from the database, even though I deleted it, it still appears in the database
> 
> ![image](https://user-images.githubusercontent.com/50597234/236694312-ca543a25-2cf4-4ffa-9a70-510f8e50ec6f.png)

Thanks, we'll check that and probably deploy a patch asap

**Comment by Jakubk15** [comment]
Or, if you want, you can do it :D

**Comment by failutee** [comment]
@Jakubk15 actually i just found the issue
