### ISSUE TITLE
Reload not work for some options.

### ISSUE THREAD

**Issue by Kamicjusz** [EternalCodeTeam/EternalCore#463]
The `/eternal reload` command currently does not work properly for functions such as. interval and draw mode in automessages.

**Comment by Rollczi** [comment]
Related:
Instance of Cache is **once** created by the constructor of the service class without reference to the config field.

**Comment by vLuckyyy** [comment]
I want to create a reload system like LobbyHeads, interface `Reloadable` with reload method. Using this interface, I want re-create this task to use a new interval from config


https://github.com/EternalCodeTeam/EternalCore/blob/master/eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageService.java#L66-L72
