### ISSUE TITLE
Center tag is not working properly.

### ISSUE THREAD

**Issue by failutee** [EternalCodeTeam/EternalCore#537]
**Describe the bug**
The line without bold is positioned correctly, while the first line with bold is moved to the right
Config => `"<b><center>SIEMA TO JEST TEKST XD</center></b><newline><center>SIEMA TO JEST TEKST XD</center>"`

**Expected behavior**
The tag should be positioned in the middle, regardless of the bold or color assigned

**Screenshots**
![image](https://github.com/EternalCodeTeam/EternalCore/assets/50597234/5cebc41c-fdde-4f8e-ac9e-cad8d0ba108c)

**Platform:**
 - Java Version: 17
 - Server software: PaperMC#194 1.20.1

**Comment by vLuckyyy** [comment]
<center><b>SIEMA TO JEST TEKST XD</b></center>

**Comment by failutee** [comment]
> Try: `<center><b>SIEMA TO JEST TEKST XD</b></center>`

I tried, the error still occurs

**Comment by vLuckyyy** [comment]
> > Try: `<center><b>SIEMA TO JEST TEKST XD</b></center>`
> 
> I tried, the error still occurs

Honestly, I'm not a fan of centering messages in Minecraft, it's not responsive and as soon as the player changes the chat width to a slightly larger one, it won't be perfectly centered, **maybe** one of us will try to fix it someday, but probably not soon, if Minecraft introduced an option to download the chat width, it would be much nicer and I think it would make sense then.
