### ISSUE TITLE
Add option to rtp to specific world.

### ISSUE THREAD

**Issue by vLuckyyy** [EternalCodeTeam/EternalCore#540]
Introduce a configurable feature that allows for random player teleportation when utilizing the `/rtp` command within a designated world. For instance, if a server administrator configures EternalCore to enable teleportation exclusively within a particular world, and a player attempts to use the `/rtp` command in the `world_nether`, this command will then initiate random teleportation, relocating the player to the specified `world`.

**Comment by ChudziudgiToJa** [comment]
tata ja to naprawie tata zostaw wideło
