### ISSUE TITLE
Boykisser functionality

### ISSUE THREAD

**Issue by P3ridot** [EternalCodeTeam/EternalCore#656]
So I can become real boykisser in Minecraft UwU

**Comment by Rollczi** [comment]
![image](https://media.tenor.com/bvA_fkqTZboAAAAi/boykisser.gif)

**Comment by P3ridot** [comment]
ETA? I need that ASAP

**Comment by Rollczi** [comment]
> So I can become real boykisser in Minecraft UwU

We need more specifications and more details to implement this. When we get more information, it will be easier for us to estimate the time.

**Comment by P3ridot** [comment]
It would be pretty straight forward

1. You create GenderService where you can declare your gender as Boy, Girl, Nonbinary and None (default one)
2. You create BoykisserService and method `tryToKissBoy` where you pass 2 player (kisser and kisserTarget). This method result boolean (true if kisserTarget is boy and false if kisserTarget is not boy), also you put that data in database so you can  check in future by calling `isBoyKisser`. Also after kissing both of players receive heart particles around them for 1 minute

**Comment by P3ridot** [comment]
Sadek

**Comment by Rollczi** [comment]
????
