### ISSUE TITLE
Don't count vanished players in list and online command.

### ISSUE THREAD

**Issue by HonzasikCZ** [EternalCodeTeam/EternalCore#696]
**Is your feature request related to a problem? Please describe.**
If someone has vanish, placeholder {ONLINE} will also show players with vanish

**Describe the solution you'd like**
add supervanish plugin support so placeholder {ONLINE} works properly when someone has vanish

**Describe alternatives you've considered**

**Additional context**
one player now has vanish:
![obrazek](https://github.com/EternalCodeTeam/EternalCore/assets/94143975/2cc11f66-b4c6-485a-8922-53cf30476ca3)

**Comment by vLuckyyy** [comment]
I will add this today.

**Comment by vLuckyyy** [comment]
![image](https://github.com/EternalCodeTeam/EternalCore/assets/65517973/a652156b-2a17-4c5b-9775-75c972ea129c)
