### ISSUE TITLE
Add option world for /butcher command

### ISSUE THREAD

**Issue by HonzasikCZ** [EternalCodeTeam/EternalCore#721]
**Is your feature request related to a problem? Please describe.**
I want to killmobs only in one world but i cant

**Describe the solution you'd like**
You write name of the world and plugin will kill all mobs in the world

**Describe alternatives you've considered**
idk

**Additional context**
idk

**Comment by vLuckyyy** [comment]
The butcher's current method for calculating the number of "chunks" from which mobs are removed is based on the player's position. However, a potential issue arises when a player is in world X but wants to remove mobs from a range of five chunks in world Y. How does eternalcore determine which chunks should be included in the butcher's scope in this scenario?

**Comment by vLuckyyy** [comment]
> Member

@HonzasikCZ

**Comment by vLuckyyy** [comment]
> The butcher's current method for calculating the number of "chunks" from which mobs are removed is based on the player's position. However, a potential issue arises when a player is in world X but wants to remove mobs from a range of five chunks in world Y. How does eternalcore determine which chunks should be included in the butcher's scope in this scenario?

@HonzasikCZ

**Comment by vLuckyyy** [comment]
I can't do it, I don't know how to do it, explain your vision for this function.
