### ISSUE TITLE
Message type for Spawn teleport (eg. Bossbar, ActionBar, Title, Chat)

### ISSUE THREAD

**Issue by vLuckyyy** [EternalCodeTeam/EternalCore#80]

**Comment by Osnixer** [comment]
Zrobić pobieranie wiadomości:

key: "[TITLE]&6Wiadomość" - title
key: "[SUBTITLE]&6Wiadomość" - subtitle
key: "[TITLES]&6Wiadomość" - title & subtitle
key: "[ACTIONBAR]&6Wiadomość" - actionbar
key: "&6Wiadomość" - chat defaultowo
