### ISSUE TITLE
Title and SubTitle not working

### ISSUE THREAD

**Issue by failutee** [EternalCodeTeam/EternalCore#811]
As in the description, title and subtitle does not work.

Example:
```
offlinePlayer:
  title: "<red>✘ <dark_red>Błąd: <red>Ten gracz jest obecnie offline!"
  times: "1s 1s 1s"
```

(No errors in the console)

![image](https://github.com/user-attachments/assets/61917965-1253-4dc7-9d4d-89326768ccd9)
![image](https://github.com/user-attachments/assets/99bbdf37-c95d-4e6a-9a21-8eab5476e4ec)

**Comment by igoyek** [comment]
I took a look at it, classic - it works for me.
```
offlinePlayer:
    title: "<red>✘ <dark_red>Błąd: <red>Ten gracz jest obecnie offline!"
    times: "1s 1s 1s"
```
![image](https://github.com/user-attachments/assets/08d9f9a7-aebb-4f5e-add6-a85df45700d7)

Maybe just update plugin version, i think it's solution :)

![image](https://github.com/user-attachments/assets/2facd77a-7091-474a-8267-1ccb4774cd52)

**Comment by failutee** [comment]
Martin recently fixed it, when I created the issue it didn't work
