### ISSUE TITLE
Teleport to default home

### ISSUE THREAD

**Issue by igoyek** [EternalCodeTeam/EternalCore#830]
A friend suggested that the "/home" command without arguments should not send correct usage, but teleport to a home with a default name (default "home") if the player has one. If not - send correct usage with a list of houses.

![image](https://github.com/user-attachments/assets/a0e6a3c6-2bd4-4172-8a4c-bcd8bbfb15f0)
`/home` can teleport to home "home"

**Comment by vLuckyyy** [comment]
This should have already been added, are you sure you checked it?
